package wrap

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path"
	"sort"
	"strings"
	"text/template"

	"github.com/emicklei/proto"
	"github.com/sllt/pi/pkg/pi/cli/helper"
	"github.com/sllt/pi/pkg/pi/version"
)

const (
	filePerm                = 0644
	serverFileSuffix        = "_server.go"
	serverWrapperFileSuffix = "_pi.go"
	clientFileSuffix        = "_client.go"
	clientHealthFile        = "health_client.go"
	serverHealthFile        = "health_pi.go"
	serverRequestFile       = "request_pi.go"
)

var (
	ErrNoProtoFile        = errors.New("proto file path is required")
	ErrOpeningProtoFile   = errors.New("error opening the proto file")
	ErrFailedToParseProto = errors.New("failed to parse proto file")
	ErrGeneratingWrapper  = errors.New("error while generating the code using proto file")
	ErrWritingFile        = errors.New("error writing the generated code to the file")
)

// ServiceMethod represents a method in a proto service.
type ServiceMethod struct {
	Name            string
	Request         string
	Response        string
	StreamsRequest  bool
	StreamsResponse bool
}

// ProtoService represents a service in a proto file.
type ProtoService struct {
	Name    string
	Methods []ServiceMethod
}

// WrapperData is the template data structure.
type WrapperData struct {
	Version     string
	FullService string
	Package     string
	Service     string
	Methods     []ServiceMethod
	Requests    []string
	Source      string
}

type FileType struct {
	FileSuffix    string
	CodeGenerator func(*WrapperData) string
}

// BuildGRPCPiClient generates gRPC client wrapper code based on a proto definition.
func BuildGRPCPiClient(protoPath, outDir string) (string, error) {
	gRPCClient := []FileType{
		{FileSuffix: clientFileSuffix, CodeGenerator: generatePiClient},
		{FileSuffix: clientHealthFile, CodeGenerator: generatePiClientHealth},
	}

	return generateWrapper(protoPath, outDir, gRPCClient...)
}

// BuildGRPCPiServer generates gRPC server code based on a proto definition.
func BuildGRPCPiServer(protoPath, outDir string) (string, error) {
	gRPCServer := []FileType{
		{FileSuffix: serverWrapperFileSuffix, CodeGenerator: generatePiServerWrapper},
		{FileSuffix: serverHealthFile, CodeGenerator: generatePiServerHealthWrapper},
		{FileSuffix: serverRequestFile, CodeGenerator: generatePiRequestWrapper},
		{FileSuffix: serverFileSuffix, CodeGenerator: generatePiServer},
	}

	return generateWrapper(protoPath, outDir, gRPCServer...)
}

// generateWrapper executes the function for specified FileType to create Pi integrated
// gRPC server/client files with the required services in proto file and
// specified suffix for every service specified in the proto file.
func generateWrapper(protoPath, outDir string, options ...FileType) (string, error) {
	if protoPath == "" {
		return "", ErrNoProtoFile
	}

	definition, err := parseProtoFile(protoPath)
	if err != nil {
		return "", err
	}

	projectPath, packageName := getPackageAndProject(definition, protoPath, outDir)
	services := getServices(definition)
	requests := getRequests(services)

	if err := os.MkdirAll(projectPath, os.ModePerm); err != nil {
		return "", fmt.Errorf("error creating output directory: %w", err)
	}

	var messages []string
	files := map[string]helper.File{}
	protoPackage := ""
	proto.Walk(definition, proto.WithPackage(func(p *proto.Package) { protoPackage = p.Name }))

	for _, service := range services {
		wrapperData := WrapperData{
			Version:     version.Framework,
			FullService: strings.TrimPrefix(protoPackage+"."+service.Name, "."),
			Package:     packageName,
			Service:     service.Name,
			Methods:     service.Methods,
			Requests:    uniqueRequestTypes(service.Methods),
			Source:      path.Base(protoPath),
		}

		for _, option := range options {
			if option.FileSuffix == serverRequestFile {
				wrapperData.Requests = requests
			}
			name := getOutputFilePath(projectPath, service.Name, option.FileSuffix)
			old, readErr := os.ReadFile(name)
			if readErr == nil {
				if option.FileSuffix == serverFileSuffix {
					messages = append(messages, "Preserved: "+name)
					continue
				}
				if !bytes.HasPrefix(old, []byte("// Code generated by pi-cli.")) {
					return "", fmt.Errorf("refusing to overwrite handwritten file: %s", name)
				}
			} else if !os.IsNotExist(readErr) {
				return "", readErr
			}
			code := option.CodeGenerator(&wrapperData)
			if code == "" {
				return "", ErrGeneratingWrapper
			}
			files[name] = helper.File{Data: []byte(code), Replace: readErr == nil}
			messages = append(messages, "Generated: "+name)
		}
	}
	if err := helper.WriteFiles(files); err != nil {
		return "", err
	}

	return strings.Join(messages, "\n"), nil
}

// parseProtoFile opens and parses the proto file.
func parseProtoFile(protoPath string) (*proto.Proto, error) {
	file, err := os.Open(protoPath)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrOpeningProtoFile, err)
	}
	defer file.Close()

	parser := proto.NewParser(file)

	definition, err := parser.Parse()
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrFailedToParseProto, err)
	}

	return definition, nil
}

// generateFiles generates files for a given service.
func generateFiles(projectPath, serviceName string, wrapperData *WrapperData,
	requests []string, options ...FileType) ([]string, error) {
	var messages []string

	for _, option := range options {
		if option.FileSuffix == serverRequestFile {
			wrapperData.Requests = requests
		}

		generatedCode := option.CodeGenerator(wrapperData)
		if generatedCode == "" {
			return nil, fmt.Errorf("%w: service %s, suffix %s", ErrGeneratingWrapper, serviceName, option.FileSuffix)
		}

		outputFilePath := getOutputFilePath(projectPath, serviceName, option.FileSuffix)

		// Skip server skeleton file if it already exists
		if option.FileSuffix == serverFileSuffix {
			if _, err := os.Stat(outputFilePath); err == nil {
				messages = append(messages, fmt.Sprintf("Skipped: %s (already exists)", outputFilePath))
				continue
			}
		}

		if err := os.WriteFile(outputFilePath, []byte(generatedCode), filePerm); err != nil {
			return nil, fmt.Errorf("%w: %v", ErrWritingFile, err)
		}

		messages = append(messages, fmt.Sprintf("Generated: %s", outputFilePath))
	}

	return messages, nil
}

// getOutputFilePath generates the output file path based on the file suffix.
func getOutputFilePath(projectPath, serviceName, fileSuffix string) string {
	switch fileSuffix {
	case clientHealthFile:
		return path.Join(projectPath, clientHealthFile)
	case serverHealthFile:
		return path.Join(projectPath, serverHealthFile)
	case serverRequestFile:
		return path.Join(projectPath, serverRequestFile)
	default:
		return path.Join(projectPath, strings.ToLower(serviceName)+fileSuffix)
	}
}

// getRequests extracts all unique request types from the services.
func getRequests(services []ProtoService) []string {
	requests := make(map[string]bool)

	for _, service := range services {
		for _, method := range service.Methods {
			requests[method.Request] = true
		}
	}

	return mapKeysToSlice(requests)
}

// uniqueRequestTypes extracts unique request types from methods.
func uniqueRequestTypes(methods []ServiceMethod) []string {
	requests := make(map[string]bool)

	for _, method := range methods {
		requests[method.Request] = true
	}

	return mapKeysToSlice(requests)
}

// mapKeysToSlice converts a map's keys to a slice.
func mapKeysToSlice(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	return keys
}

// executeTemplate executes a template with the provided data.
func executeTemplate(data *WrapperData, tmpl string) string {
	funcMap := template.FuncMap{
		"lowerFirst": func(s string) string {
			if s == "" {
				return ""
			}
			return strings.ToLower(s[:1]) + s[1:]
		},
	}

	tmplInstance := template.Must(template.New("template").Funcs(funcMap).Parse(tmpl))

	var buf bytes.Buffer

	if err := tmplInstance.Execute(&buf, data); err != nil {
		return ""
	}

	return buf.String()
}

// Template generators.
func generatePiServerWrapper(data *WrapperData) string {
	return executeTemplate(data, wrapperTemplate)
}

func generatePiRequestWrapper(data *WrapperData) string {
	return executeTemplate(data, messageTemplate)
}

func generatePiServerHealthWrapper(data *WrapperData) string {
	return executeTemplate(data, healthServerTemplate)
}

func generatePiClientHealth(data *WrapperData) string {
	return executeTemplate(data, clientHealthTemplate)
}

func generatePiServer(data *WrapperData) string {
	return executeTemplate(data, serverTemplate)
}

func generatePiClient(data *WrapperData) string {
	return executeTemplate(data, clientTemplate)
}

// getPackageAndProject extracts the package name and project path from the proto definition.
// If outDir is provided, it is used as the project path instead of the proto file's directory.
// When outDir is provided, the package name is derived from the last segment of outDir.
func getPackageAndProject(definition *proto.Proto, protoPath, outDir string) (projectPath, packageName string) {
	proto.Walk(definition,
		proto.WithOption(func(opt *proto.Option) {
			if opt.Name == "go_package" {
				packageName = path.Base(opt.Constant.Source)
				if parts := strings.Split(packageName, ";"); len(parts) == 2 {
					packageName = parts[1]
				}
			}
		}),
	)

	if outDir != "" {
		projectPath = outDir
		packageName = path.Base(outDir)
	} else {
		projectPath = path.Dir(protoPath)
	}

	return projectPath, packageName
}

// getServices extracts services from the proto definition.
func getServices(definition *proto.Proto) []ProtoService {
	var services []ProtoService

	proto.Walk(definition,
		proto.WithService(func(s *proto.Service) {
			service := ProtoService{Name: s.Name}

			for _, element := range s.Elements {
				if rpc, ok := element.(*proto.RPC); ok {
					service.Methods = append(service.Methods, ServiceMethod{
						Name:            rpc.Name,
						Request:         rpc.RequestType,
						Response:        rpc.ReturnsType,
						StreamsRequest:  rpc.StreamsRequest,
						StreamsResponse: rpc.StreamsReturns,
					})
				}
			}

			services = append(services, service)
		}),
	)

	return services
}
