// Code generated by pi-cli. DO NOT EDIT.
// versions:
// 	pi-cli v0.4.1
// 	pi v0.4.1
// 	source: hello.proto

package server

import (
	"context"

	"github.com/sllt/pi/pkg/pi"
	piGRPC "github.com/sllt/pi/pkg/pi/grpc"
	"github.com/sllt/pi/pkg/pi/infra"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	healthpb "google.golang.org/grpc/health/grpc_health_v1"
)

// NewHelloPiServer creates a new instance of HelloPiServer
func NewHelloPiServer() *HelloPiServer {
	return &HelloPiServer{
		health: getOrCreateHealthServer(), // Initialize the health server
	}
}

// HelloServerWithPi is the interface for the server implementation
type HelloServerWithPi interface {
	SayHello(*pi.Context) (any, error)
}

// HelloServerWrapper wraps the server and handles request and response logic
type HelloServerWrapper struct {
	HelloServer
	*healthServer
	Container *infra.Container
	app       *pi.App
	server    HelloServerWithPi
}

// Unary method handler for SayHello
func (h *HelloServerWrapper) SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	gctx := h.getPiContext(ctx, &HelloRequestWrapper{ctx: ctx, HelloRequest: req})

	res, err := h.server.SayHello(gctx)
	if err != nil {
		return nil, piGRPC.MapError(err)
	}

	resp, ok := res.(*HelloResponse)
	if !ok {
		return nil, status.Error(codes.Internal, "internal server error")
	}

	return resp, nil
}

// mustEmbedUnimplementedHelloServer ensures implementation
func (h *HelloServerWrapper) mustEmbedUnimplementedHelloServer() {}

// RegisterHelloServerWithPi registers the server
func RegisterHelloServerWithPi(app *pi.App, srv HelloServerWithPi) {
	registerServerWithPi(app, srv, func(s grpc.ServiceRegistrar, srv any) {
		wrapper := &HelloServerWrapper{
			server:       srv.(HelloServerWithPi),
			healthServer: &healthServer{app.GRPCHealthServer()},
			app:          app,
		}

		RegisterHelloServer(s, wrapper)

		wrapper.healthServer.Server.SetServingStatus("Hello", healthpb.HealthCheckResponse_SERVING)
	})
}

// getPiContext creates Pi context
func (h *HelloServerWrapper) getPiContext(ctx context.Context, req pi.Request) *pi.Context {
	c := h.app.NewContext(ctx)
	c.Request = req
	return c
}
