// Code generated by github.com/sllt/pi/cli/pi. DO NOT EDIT.
// versions:
// 	pi-cli v0.7.0
// 	github.com/sllt/pi v1.39.0
// 	source: hello.proto

package server

import (
	"context"
	"time"

	"github.com/sllt/pi/pkg/pi"
	pigRPC "github.com/sllt/pi/pkg/pi/grpc"
	"github.com/sllt/pi/pkg/pi/infra"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	healthpb "google.golang.org/grpc/health/grpc_health_v1"
)

// NewHelloPiServer creates a new instance of HelloPiServer
func NewHelloPiServer() *HelloPiServer {
	return &HelloPiServer{
		health: getOrCreateHealthServer(), // Initialize the health server
	}
}

// HelloServerWithPi is the interface for the server implementation
type HelloServerWithPi interface {
	SayHello(*pi.Context) (any, error)
}

// HelloServerWrapper wraps the server and handles request and response logic
type HelloServerWrapper struct {
	HelloServer
	*healthServer
	Container *infra.Container
	server    HelloServerWithPi
}

// Base instrumented stream
type instrumentedStream struct {
	grpc.ServerStream
	ctx    *pi.Context
	method string
}

func (s *instrumentedStream) Context() context.Context {
	return s.ctx
}

func (s *instrumentedStream) SendMsg(m interface{}) error {
	start := time.Now()
	span := s.ctx.Trace(s.method + "/SendMsg")
	defer span.End()

	err := s.ServerStream.SendMsg(m)

	logger := pigRPC.NewgRPCLogger()
	logger.DocumentRPCLog(s.ctx, s.ctx.Logger, s.ctx.Metrics(), start, err,
		s.method+"/SendMsg", "app_gRPC-Stream_stats")

	return err
}

func (s *instrumentedStream) RecvMsg(m interface{}) error {
	start := time.Now()
	span := s.ctx.Trace(s.method + "/RecvMsg")
	defer span.End()

	err := s.ServerStream.RecvMsg(m)

	logger := pigRPC.NewgRPCLogger()
	logger.DocumentRPCLog(s.ctx, s.ctx.Logger, s.ctx.Metrics(), start, err,
		s.method+"/RecvMsg", "app_gRPC-Stream_stats")

	return err
}

// Unary method handler for SayHello
func (h *HelloServerWrapper) SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	gctx := h.getPiContext(ctx, &HelloRequestWrapper{ctx: ctx, HelloRequest: req})

	res, err := h.server.SayHello(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*HelloResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}

	return resp, nil
}

// mustEmbedUnimplementedHelloServer ensures implementation
func (h *HelloServerWrapper) mustEmbedUnimplementedHelloServer() {}

// RegisterHelloServerWithPi registers the server
func RegisterHelloServerWithPi(app *pi.App, srv HelloServerWithPi) {
	registerServerWithPi(app, srv, func(s grpc.ServiceRegistrar, srv any) {
		wrapper := &HelloServerWrapper{
			server:       srv.(HelloServerWithPi),
			healthServer: getOrCreateHealthServer(),
		}

		RegisterHelloServer(s, wrapper)

		wrapper.Server.SetServingStatus("Hello", healthpb.HealthCheckResponse_SERVING)
	})
}

// getPiContext creates Pi context
func (h *HelloServerWrapper) getPiContext(ctx context.Context, req pi.Request) *pi.Context {
	return &pi.Context{
		Context:   ctx,
		Container: h.Container,
		Request:   req,
	}
}
