// Code generated by pi-cli. DO NOT EDIT.
// versions:
// 	pi-cli v0.4.1
// 	pi v0.4.1
// 	source: hello.proto

package server

import (
	"context"
	piGRPC "github.com/sllt/pi/pkg/pi/grpc"
)

// Request Wrappers
type HelloRequestWrapper struct {
	ctx context.Context
	*HelloRequest
}

func (h *HelloRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *HelloRequestWrapper) Param(s string) string {
	return ""
}

func (h *HelloRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *HelloRequestWrapper) Bind(p interface{}) error {
	return piGRPC.BindRequest(p, h.HelloRequest)
}

func (h *HelloRequestWrapper) HostName() string {
	return ""
}

func (h *HelloRequestWrapper) Params(s string) []string {
	return nil
}
