// Code generated by pi-cli. DO NOT EDIT.
// versions:
// 	pi-cli v0.4.1
// 	pi v0.4.1
// 	source: hello.proto

package client

import (
	"github.com/sllt/pi/pkg/pi"
	"github.com/sllt/pi/pkg/pi/metrics"
	"google.golang.org/grpc"
)

type HelloPiClient interface {
	SayHello(ctx *pi.Context, req *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	HealthClient
}

type HelloClientWrapper struct {
	client HelloClient
	HealthClient
}

func NewHelloPiClient(host string, metrics metrics.Manager, dialOptions ...grpc.DialOption) (HelloPiClient, error) {
	conn, err := createGRPCConn(host, "Hello", dialOptions...)
	if err != nil {
		return &HelloClientWrapper{
			client:       nil,
			HealthClient: &HealthClientWrapper{client: nil},
		}, err
	}

	metricsOnce.Do(func() {
		metrics.NewHistogram("app_gRPC-Client_stats", "Response time of gRPC client in milliseconds.", gRPCBuckets...)
	})

	res := NewHelloClient(conn)
	healthClient := NewHealthClient(conn)

	return &HelloClientWrapper{
		client:       res,
		HealthClient: healthClient,
	}, nil
}

func (h *HelloClientWrapper) SayHello(ctx *pi.Context, req *HelloRequest,
	opts ...grpc.CallOption) (*HelloResponse, error) {
	result, err := invokeRPC(ctx, "/Hello/SayHello", func() (interface{}, error) {
		return h.client.SayHello(ctx.Context, req, opts...)
	}, "app_gRPC-Client_stats")

	if err != nil {
		return nil, err
	}
	return result.(*HelloResponse), nil
}
