// Code generated by pi-cli. DO NOT EDIT.
// versions:
// 	pi-cli v0.4.1
// 	pi v0.4.1
// 	source: chat.proto

package server

import (
	"context"
	"time"

	"github.com/sllt/pi/pkg/pi"
	piGRPC "github.com/sllt/pi/pkg/pi/grpc"
	"github.com/sllt/pi/pkg/pi/infra"
	"google.golang.org/grpc"

	healthpb "google.golang.org/grpc/health/grpc_health_v1"
)

// NewChatServicePiServer creates a new instance of ChatServicePiServer
func NewChatServicePiServer() *ChatServicePiServer {
	return &ChatServicePiServer{
		health: getOrCreateHealthServer(), // Initialize the health server
	}
}

// ChatServiceServerWithPi is the interface for the server implementation
type ChatServiceServerWithPi interface {
	ServerStream(*pi.Context, ChatService_ServerStreamServer) error
	ClientStream(*pi.Context, ChatService_ClientStreamServer) error
	BiDiStream(*pi.Context, ChatService_BiDiStreamServer) error
}

// ChatServiceServerWrapper wraps the server and handles request and response logic
type ChatServiceServerWrapper struct {
	ChatServiceServer
	*healthServer
	Container *infra.Container
	app       *pi.App
	server    ChatServiceServerWithPi
}

// Base instrumented stream
type instrumentedStreamChatService struct {
	grpc.ServerStream
	ctx    *pi.Context
	method string
}

func (s *instrumentedStreamChatService) Context() context.Context {
	return s.ctx
}

func (s *instrumentedStreamChatService) SendMsg(m interface{}) error {
	start := time.Now()
	span := s.ctx.Trace(s.method + "/SendMsg")
	defer span.End()

	err := s.ServerStream.SendMsg(m)

	logger := piGRPC.NewgRPCLogger()
	logger.DocumentRPCLog(s.ctx, s.ctx.Logger, s.ctx.Metrics(), start, err,
		s.method+"/SendMsg", "app_gRPC-Stream_stats")

	return err
}

func (s *instrumentedStreamChatService) RecvMsg(m interface{}) error {
	start := time.Now()
	span := s.ctx.Trace(s.method + "/RecvMsg")
	defer span.End()

	err := s.ServerStream.RecvMsg(m)

	logger := piGRPC.NewgRPCLogger()
	logger.DocumentRPCLog(s.ctx, s.ctx.Logger, s.ctx.Metrics(), start, err,
		s.method+"/RecvMsg", "app_gRPC-Stream_stats")

	return err
}

// Server-side streaming specific wrapper
type serverStreamWrapperChatServiceServerStream struct {
	*instrumentedStreamChatService
}

func (w *serverStreamWrapperChatServiceServerStream) Send(m *Response) error {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/Send")
	defer span.End()

	err := w.ServerStream.SendMsg(m)

	logger := piGRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
		w.method+"/Send", "app_gRPC-Stream_stats")

	return err
}

// Client-side streaming specific wrapper
type clientStreamWrapperChatServiceClientStream struct {
	*instrumentedStreamChatService
}

func (w *clientStreamWrapperChatServiceClientStream) SendAndClose(m *Response) error {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/SendAndClose")
	defer span.End()

	err := w.ServerStream.SendMsg(m)

	logger := piGRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
		w.method+"/SendAndClose", "app_gRPC-Stream_stats")

	return err
}

func (w *clientStreamWrapperChatServiceClientStream) Recv() (*Request, error) {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/Recv")
	defer span.End()

	var req Request
	err := w.ServerStream.RecvMsg(&req)

	logger := piGRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
		w.method+"/Recv", "app_gRPC-Stream_stats")

	return &req, err
}

// Client-side streaming specific wrapper
type clientStreamWrapperChatServiceBiDiStream struct {
	*instrumentedStreamChatService
}

func (w *clientStreamWrapperChatServiceBiDiStream) SendAndClose(m *Response) error {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/SendAndClose")
	defer span.End()

	err := w.ServerStream.SendMsg(m)

	logger := piGRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
		w.method+"/SendAndClose", "app_gRPC-Stream_stats")

	return err
}

func (w *clientStreamWrapperChatServiceBiDiStream) Recv() (*Request, error) {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/Recv")
	defer span.End()

	var req Request
	err := w.ServerStream.RecvMsg(&req)

	logger := piGRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
		w.method+"/Recv", "app_gRPC-Stream_stats")

	return &req, err
}

// Bidirectional streaming wrapper
type bidiStreamWrapperChatServiceBiDiStream struct {
	*instrumentedStreamChatService
}

func (w *bidiStreamWrapperChatServiceBiDiStream) Send(m *Response) error {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/Send")
	defer span.End()

	err := w.ServerStream.SendMsg(m)

	logger := piGRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
		w.method+"/Send", "app_gRPC-Stream_stats")

	return err
}

func (w *bidiStreamWrapperChatServiceBiDiStream) Recv() (*Request, error) {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/Recv")
	defer span.End()

	var req Request
	err := w.ServerStream.RecvMsg(&req)

	logger := piGRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
		w.method+"/Recv", "app_gRPC-Stream_stats")

	return &req, err
}

func (w *bidiStreamWrapperChatServiceBiDiStream) CloseSend() error {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/CloseSend")
	defer span.End()

	err := w.ServerStream.(grpc.ClientStream).CloseSend()

	logger := piGRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
		w.method+"/CloseSend", "app_gRPC-Stream_stats")

	return err
}

// Server-side streaming handler for ServerStream
func (h *ChatServiceServerWrapper) ServerStream(req *Request, stream ChatService_ServerStreamServer) error {
	ctx := stream.Context()
	gctx := h.getPiContext(ctx, &RequestWrapper{ctx: ctx, Request: req})

	is := &instrumentedStreamChatService{
		ServerStream: stream,
		ctx:          gctx,
		method:       "/ChatService/ServerStream",
	}

	wrappedStream := &serverStreamWrapperChatServiceServerStream{instrumentedStreamChatService: is}
	return piGRPC.MapError(h.server.ServerStream(gctx, wrappedStream))
}

// Client-side streaming handler for ClientStream
func (h *ChatServiceServerWrapper) ClientStream(stream ChatService_ClientStreamServer) error {
	ctx := stream.Context()
	gctx := h.getPiContext(ctx, nil)

	is := &instrumentedStreamChatService{
		ServerStream: stream,
		ctx:          gctx,
		method:       "/ChatService/ClientStream",
	}

	wrappedStream := &clientStreamWrapperChatServiceClientStream{instrumentedStreamChatService: is}
	return piGRPC.MapError(h.server.ClientStream(gctx, wrappedStream))
}

// Bidirectional streaming handler for BiDiStream
func (h *ChatServiceServerWrapper) BiDiStream(stream ChatService_BiDiStreamServer) error {
	ctx := stream.Context()
	gctx := h.getPiContext(ctx, nil)

	is := &instrumentedStreamChatService{
		ServerStream: stream,
		ctx:          gctx,
		method:       "/ChatService/BiDiStream",
	}

	wrappedStream := &bidiStreamWrapperChatServiceBiDiStream{instrumentedStreamChatService: is}
	return piGRPC.MapError(h.server.BiDiStream(gctx, wrappedStream))
}

// mustEmbedUnimplementedChatServiceServer ensures implementation
func (h *ChatServiceServerWrapper) mustEmbedUnimplementedChatServiceServer() {}

// RegisterChatServiceServerWithPi registers the server
func RegisterChatServiceServerWithPi(app *pi.App, srv ChatServiceServerWithPi) {
	registerServerWithPi(app, srv, func(s grpc.ServiceRegistrar, srv any) {
		wrapper := &ChatServiceServerWrapper{
			server:       srv.(ChatServiceServerWithPi),
			healthServer: &healthServer{app.GRPCHealthServer()},
			app:          app,
		}

		RegisterChatServiceServer(s, wrapper)

		wrapper.healthServer.Server.SetServingStatus("ChatService", healthpb.HealthCheckResponse_SERVING)
	})
}

// getPiContext creates Pi context
func (h *ChatServiceServerWrapper) getPiContext(ctx context.Context, req pi.Request) *pi.Context {
	c := h.app.NewContext(ctx)
	c.Request = req
	return c
}
