// Code generated by pi-cli. DO NOT EDIT.
// versions:
// 	pi-cli v0.4.1
// 	pi v0.4.1
// 	source: chat.proto

package server

import (
	"context"
	piGRPC "github.com/sllt/pi/pkg/pi/grpc"
)

// Request Wrappers
type RequestWrapper struct {
	ctx context.Context
	*Request
}

func (h *RequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *RequestWrapper) Param(s string) string {
	return ""
}

func (h *RequestWrapper) PathParam(s string) string {
	return ""
}

func (h *RequestWrapper) Bind(p interface{}) error {
	return piGRPC.BindRequest(p, h.Request)
}

func (h *RequestWrapper) HostName() string {
	return ""
}

func (h *RequestWrapper) Params(s string) []string {
	return nil
}
